language: node_js
node_js:
- 6
script:
- npm test
- npm run build
deploy:
  provider: releases
  api_key:
    secure: MoCeQYRmsMEFLPOn7y63LP8XeeKmb+g1Rs3K04bYcApS7q5j8V6p/nNnAMKKFXjbf5BNG9aVrUCoO1maFO6QqDmygX5tG+sbMi03btq/i1pmkjCg+sEmmkkhO9Wuawg2wPjRwU/qV3pK9p+zzNgXDw9ccPdZjinDFoi08+vPcxU=
  file:
    - out/index.min.js
    - out/index-silent.js
    - out/index.css
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
